eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
    
    

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF


